name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    name: Security
    steps:
      - uses: holepunchto/actions/security-base@v1
  test:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm test
